---
# This workflow will create a release with artifacts created by other workflow uploaded, whenever a new tag is created.

name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  pyinstaller:
    uses: ./.github/workflows/pyinstaller.yml

  create-release:
    runs-on: ubuntu-latest
    needs: [pyinstaller]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
        git config user.name "${{ secrets.GITHUB_ACTOR }}"

    - name: Download Artifacts
      uses: actions/download-artifact@v2

    - name: Create Release
      run: |
        tag=$(git describe --tags --abbrev=0)
        echo "Creating release for tag $tag"
        mv a10y-linux-x86_64/dist/a10y . && rm -rf a10y-linux-x86_64 && mv a10y a10y-linux-x86_64
        mv a10y-win.exe/dist/a10y.exe . && rm -rf a10y-win.exe && mv a10y.exe a10y-win.exe
        mv a10y-macos.exe/dist/a10y . && rm -rf a10y-macos.exe && mv a10y a10y-macos.exe
        gh release create "$tag" a10y-linux-x86_64 a10y-win.exe a10y-macos.exe
