name: Test GitHub Secrets

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:

      - name: Check for GitHub Token
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "❌ GITHUB_TOKEN is NOT set!"
            exit 1
          else
            echo "✅ GITHUB_TOKEN exists!"
          fi
